name: Run Continuous Tests


on:
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - 'v*.*.*'
  #   paths-ignore:
  #     - '**/*.md'
  #     - '.gitignore'
  #     - 'docker/**'
  #     - '!docker/continuous-tests-job.yaml'
  workflow_dispatch:
    inputs:
      source:
        description: Repository with tests (current)
        required: false
        type: string
      branch:
        description: Branch with tests (master)
        required: false
        type: string
      nameprefix:
        description: Runner name prefix (c-tests-runner)
        required: false
        type: string
      namespace:
        description: Runner namespace (default)
        required: false
        type: string
      tests_target_duration:
        description: Runner target duration (172800 = 48h)
        required: false
        type: string
      tests_filter:
        description: Runner tests filter ("")
        required: false
        type: string
      tests_cleanup:
        description: Runner tests cleanup
        type: choice
        options:
        - true
        - false
        default: true
      deployment_namespace:
        description: Deployment namespace (c-tests-$runid)
        required: false
        type: string


env:
  BRANCH: ${{ github.ref_name }}
  SOURCE: ${{ format('{0}/{1}', github.server_url, github.repository) }}
  NAMEPREFIX: c-tests-runner
  NAMESPACE: default
  DEPLOYMENT_NAMESPACE: c-tests
  TESTS_TARGET_DURATION: 172800
  TESTS_FILTER: ""
  TESTS_CLEANUP: true
  JOB_MANIFEST: docker/continuous-tests-job.yaml
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  KUBE_VERSION: v1.28.2


jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Variables
        run: |
          RUNID=$(date +%Y%m%d-%H%M%S)
          echo "RUNID=${RUNID}" >> $GITHUB_ENV
          echo "TESTID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          [[ -n "${{ github.event.inputs.source }}" ]] && echo "SOURCE=${{ github.event.inputs.source }}" >>"$GITHUB_ENV" || echo "SOURCE=${{ env.SOURCE }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.branch }}" ]] && echo "BRANCH=${{ github.event.inputs.branch }}" >>"$GITHUB_ENV" || echo "BRANCH=${{ env.BRANCH }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.nameprefix }}" ]] && echo "NAMEPREFIX=${{ github.event.inputs.nameprefix }}" >>"$GITHUB_ENV" || echo "NAMEPREFIX=${{ env.NAMEPREFIX }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.namespace }}" ]] && echo "NAMESPACE=${{ github.event.inputs.namespace }}" >>"$GITHUB_ENV" || echo "NAMESPACE=${{ env.NAMESPACE }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.tests_target_duration }}" ]] && echo "TESTS_TARGET_DURATION=${{ github.event.inputs.tests_target_duration }}" >>"$GITHUB_ENV" || echo "TESTS_TARGET_DURATION=${{ env.TESTS_TARGET_DURATION }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.tests_filter }}" ]] && echo "TESTS_FILTER=${{ github.event.inputs.tests_filter }}" >>"$GITHUB_ENV" || echo "TESTS_FILTERS=${{ env.TESTS_FILTERS }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.tests_cleanup }}" ]] && echo "TESTS_CLEANUP=${{ github.event.inputs.tests_cleanup }}" >>"$GITHUB_ENV" || echo "TESTS_CLEANUP=${{ env.TESTS_CLEANUP }}" >>"$GITHUB_ENV"
          [[ -n "${{ github.event.inputs.deployment_namespace }}" ]] && echo "DEPLOYMENT_NAMESPACE=${{ github.event.inputs.deployment_namespace }}" >>"$GITHUB_ENV" || echo "DEPLOYMENT_NAMESPACE=${{ env.DEPLOYMENT_NAMESPACE }}-${RUNID}" >>"$GITHUB_ENV"

      - name: Kubectl - Install ${{ env.KUBE_VERSION }}
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBE_VERSION }}

      - name: Kubectl - Kubeconfig
        run: |
          mkdir -p "${HOME}"/.kube
          echo "${{ env.KUBE_CONFIG }}" | base64 -d > "${HOME}"/.kube/config

      - name: Kubectl - Create Job
        run: |
          envsubst < ${{ env.JOB_MANIFEST }} | kubectl apply -f -

      - name: Tests Identification
        run: |
          echo "----"
          echo "Repository: ${{ env.SOURCE }}"
          echo "Branch: ${{ env.BRANCH }}"
          echo "Runner Pod: ${{ env.NAMEPREFIX }}-${{ env.RUNID }}"
          echo "Runner namespace: ${{ env.NAMESPACE }}"
          echo "----"
          echo "Tests namespace: ${{ env.DEPLOYMENT_NAMESPACE }}"
          echo "Tests duration: ${{ env.TESTS_TARGET_DURATION }}"
          echo "Tests filter: ${{ env.TESTS_FILTER }}"
          echo "Tests cleanup: ${{ env.TESTS_CLEANUP }}"
          echo "----"
