name: Docker - Rewarder Bot

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - 'Tools/TestNetRewarder/**'
      - '!Tools/TestNetRewarder/docker/docker-compose.yaml'
      - 'Framework/**'
      - 'ProjectPlugins/**'
      - .github/workflows/docker-rewarder.yml
      - .github/workflows/docker-reusable.yml
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    uses: ./.github/workflows/docker-reusable.yml
    with:
      docker_file: Tools/TestNetRewarder/docker/Dockerfile
      docker_repo: codexstorage/codex-rewarderbot
    secrets: inherit

