name: Docker


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - docker/Dockerfile
      - docker/docker-entrypoint.sh
      - .github/workflows/docker.yml
      - .github/workflows/docker-reusable.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: ./.github/workflows/docker-reusable.yml
    secrets: inherit
