name: Run Continuous Tests


on:
  workflow_dispatch:
    inputs:
      codexdockerimage:
        description: Codex Docker image (example: 'codexstorage/nim-codex:0.1.8-dist-tests')
        required: true
        type: string
  workflow_call:
    inputs:
      codexdockerimage:
        description: Codex Docker image (example: 'codexstorage/nim-codex:0.1.8-dist-tests')
        required: true
        type: string

env:
  JOB_MANIFEST: docker/release-tests-job.yaml
  CODEXDOCKERIMAGE: codexstorage/nim-codex:not-specified
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  KUBE_VERSION: v1.28.2

jobs:
  run_tests:
    name: Run Codex Release Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.workflow_source }}

      - name: Variables
        run: |
          [[ -n "${{ inputs.codexdockerimage }}" ]] && echo "CODEXDOCKERIMAGE=${{ inputs.codexdockerimage }}" >>"$GITHUB_ENV" || echo "CODEXDOCKERIMAGE=${{ env.CODEXDOCKERIMAGE }}" >>"$GITHUB_ENV"
          
      - name: Kubectl - Install ${{ env.KUBE_VERSION }}
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBE_VERSION }}

      - name: Kubectl - Kubeconfig
        run: |
          mkdir -p "${HOME}"/.kube
          echo "${{ env.KUBE_CONFIG }}" | base64 -d > "${HOME}"/.kube/config

      - name: Run Tests
        run: |
          dotnet test ./Tests/CodexReleaseTests
